baseURL = 'http://awesomeedl.github.io/'
languageCode = 'en-us'
title = 'Edward Liao'
theme = 'diary'

[[menu.main]]
    url = "/tags"
    name = "Tags"
    weight = 1

[[menu.main]]
  url = "/about"
  name = "About"
  weight = 2


[markup]
  [markup.highlight]
    style = 'nord'

